version: "3.7"

services:
  api:
    build: .
    depends_on:
      - "postgres"
    command: npm run dev
    environment:
      HOST: 0.0.0.0
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: faucet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      NETWORK_RPC_NODE: http://host.docker.internal:26657
      FAUCET_WAIT_PERIOD: 1m
      FAUCET_DISTRIBUTION_AMOUNT: 10000000000000000
      FAUCET_DENOM: auptick
      FAUCET_FEES: 1000
      FAUCET_GAS: 200000
      FAUCET_MEMO: Sent from Faucet
      AUTH0_DOMAIN: uptick-faucet.jp.auth0.com
      AUTH0_AUDIENCE: http://zhangboxing.com
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: faucet
    ports:
      - '5432:5432'
    volumes:
      - faucet-db:/var/lib/postgresql/data
volumes:
  faucet-db:
